### ISSUE TITLE
Browser history misbehavior

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-gui#284] opened 2021-11-29 20:15 UTC
I found this funny behavior while release testing #257. I'm using Firefox 94 on Fedora 35.

When I go back and forth between the check domain page and the result page using my browser's back and forward buttons I get some weird behavior. It starts out a bit funny before it settles on a stable and reasonable pattern from step 7.

1. I open a new tab and go to http://192.168.56.7/
2. The URL bar is set to http://192.168.56.7/domain_check, and the page view shows a "check domain" component above an "about zonemaster" component.
3. I start a test for zonemaster.net
4. When the test is completed the URL bar is set to http://192.168.56.7/result/c020fda0379befc3, and the page view shows a "result component" below a "check domain" component.
5. I press my browser's Back button.
6. The URL bar is set to http://192.168.56.7/domain_check, and the page view stays unchanged.
7. I press my browser's Forward button.
8. The URL is set to http://192.168.56.7/result/c020fda0379befc3 again, and the page view shows a "result component" below a "Result heading" component.
9. I press my browser's Back button.
10. The URL bar is set to http://192.168.56.7/domain_check, and the page view shows a "check domain" component above an "about zonemaster" component.
11. I go back to step 7.

**Comment by matsduf** [comment] 2021-11-29 22:09
@mattias-p, is this something you think we should include in the v2021.2 release? Do you think it is a bug?

**Comment by blacksponge** [comment] 2021-11-30 09:51
As I said in #257 this is the expected behaviour. Navigating to the result page, either using the history or a direct link, will result in no domain check form being displayed while having the result displayed directly after the end of the test will keep the form visible. Maybe we could think of a way to make the two more uniform but I don't think it should be done for v2021.2 as it is not a bug.

**Comment by mattias-p** [comment] 2021-12-01 10:11
I do think it's a bug. Just not a severe one. To me, having the Back button work at all is a great improvement from the last release.

When you press the Back button from the results page to get back to where you came from, you expect to actually be shown the domain check page. Merely updating the URL bar does not seem to me like a sufficient behavior for the Back button.

Also it is in fact possible to get back to the domain check page using the Back button. You just have to make two tests after each other and then press Back twice.

**Comment by blacksponge** [comment] 2021-12-01 10:54
My bad, I misunderstood step 6. In that case it is a bug, indeed.

**Comment by pnax** [comment] 2022-07-26 09:52
Fixed with #300.

**Closed by pnax** 2022-07-26 09:52 UTC
Labels: T-Bug
