### ISSUE TITLE
No redirect

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-gui#57] opened 2019-05-18 10:12 UTC
Installation from develop branch, commit fc3be71d7.

The GUI is installed according to the instructions for FreeBSD.

When I direct my browser to `http://127.0.0.1:8080/` (tunneled via SSH to 127.0.0.1:80 on virtual machine) I just get a blank page with no redirect. With `http://127.0.0.1:8080/domain_check` I get the GUI.

Installation based on commit 8717a69 gave a redirect in the same environment.

**Comment by matsduf** [comment] 2019-05-19 13:54
I cannot repeat this issue. If nobody else has seen it, we should just close this issue.

**Comment by sandoche2k** [comment] 2019-05-19 14:05
I did have a similar issue. The redirect was happening but the home page of ZM was not opening. It was fixed by @pamasse

**Comment by matsduf** [comment] 2019-05-19 14:10
@sandoche2k, wait a minute, where is that fix?

**Comment by sandoche2k** [comment] 2019-05-19 14:36
it was a direct conversation with @pamasse and I had that issue only in ubuntu.  But, it was not the same as yours. If you cannot reproduce the issue, then I think it is better to close and reopen when you encounter the issue again.

**Closed** 2019-05-19 14:46 UTC
Labels: bug
